import type { ByLevel, Vision } from './types'

// Crystal Ball: listen to a dialogue, then answer the questions.
export const VISIONS: ByLevel<Vision> = [
  // A1
  [
    {
      title: 'At the Cafe',
      a: { name: 'Mia', voice: 'f' },
      b: { name: 'Tomas', voice: 'm' },
      lines: [
        ['a', 'Hello! Can I have a tea, please?'],
        ['b', 'Sure. Hot tea or cold tea?'],
        ['a', 'Hot, please. And one cake.'],
        ['b', 'We have apple cake and lemon cake.'],
        ['a', 'Apple cake, please. How much is it?'],
        ['b', 'That is four dollars, please.'],
      ],
      questions: [
        { q: 'What drink does Mia want?', answer: 'Hot tea', wrong: ['Cold tea', 'Coffee'] },
        { q: 'Which cake does Mia choose?', answer: 'Apple cake', wrong: ['Lemon cake', 'Chocolate cake'] },
        { q: 'How much does Mia pay?', answer: 'Four dollars', wrong: ['Five dollars', 'Two dollars'] },
      ],
    },
    {
      title: 'My New Pet',
      a: { name: 'Leo', voice: 'm' },
      b: { name: 'Aiko', voice: 'f' },
      lines: [
        ['a', 'Aiko, I have a new pet!'],
        ['b', 'Oh, nice! Is it a cat?'],
        ['a', 'No, it is a small dragon.'],
        ['b', 'A dragon! What is its name?'],
        ['a', 'Its name is Spark. It is red.'],
        ['b', 'Can I see Spark tomorrow?'],
      ],
      questions: [
        { q: "What is Leo's new pet?", answer: 'A small dragon', wrong: ['A cat', 'A big dog'] },
        { q: 'What colour is Spark?', answer: 'Red', wrong: ['Green', 'Blue'] },
        { q: 'When does Aiko want to see Spark?', answer: 'Tomorrow', wrong: ['Today', 'On Sunday'] },
      ],
    },
    {
      title: 'The Lost Bag',
      a: { name: 'Omar', voice: 'm' },
      b: { name: 'Sara', voice: 'f' },
      lines: [
        ['a', "Excuse me, I can't find my bag."],
        ['b', 'What colour is your bag?'],
        ['a', 'It is blue and very big.'],
        ['b', 'Is this black bag your bag?'],
        ['a', 'No, my bag has a yellow star.'],
        ['b', 'Oh, look! Under the table!'],
      ],
      questions: [
        { q: "What colour is Omar's bag?", answer: 'Blue', wrong: ['Yellow', 'Black'] },
        { q: "What is on Omar's bag?", answer: 'A yellow star', wrong: ['A blue star', 'A red flower'] },
        { q: 'Where is the bag?', answer: 'Under the table', wrong: ['On the chair', 'In the car'] },
      ],
    },
    {
      title: 'Saturday Plans',
      a: { name: 'Priya', voice: 'f' },
      b: { name: 'Kofi', voice: 'm' },
      lines: [
        ['a', 'What do you do on Saturday?'],
        ['b', 'I play football in the park.'],
        ['a', 'Every Saturday? In the morning?'],
        ['b', 'Yes, at nine o\'clock. Come with me!'],
        ['a', "I can't. I visit my grandma."],
        ['b', 'Okay. Maybe next Saturday, then!'],
      ],
      questions: [
        { q: 'What does Kofi play?', answer: 'Football', wrong: ['Tennis', 'Basketball'] },
        { q: 'What time does Kofi play?', answer: "At nine o'clock", wrong: ["At ten o'clock", 'In the evening'] },
        { q: 'Who does Priya visit?', answer: 'Her grandma', wrong: ['Her brother', 'Her teacher'] },
      ],
    },
  ],
  // A2
  [
    {
      title: 'On the Train',
      a: { name: 'Hana', voice: 'f' },
      b: { name: 'Diego', voice: 'm' },
      lines: [
        ['a', 'Excuse me, is this seat free?'],
        ['b', 'Yes, it is. Are you going to Brookfield too?'],
        ['a', "No, I'm getting off at Millbridge. Is it the next stop?"],
        ['b', 'No, Millbridge is after Brookfield. It\'s about forty minutes from here.'],
        ['a', 'Oh, good. I have time to read my book, then.'],
        ['b', 'The cafe car is at the back, if you want a drink.'],
        ['a', 'Thanks! I forgot my water bottle at home.'],
      ],
      questions: [
        { q: 'Where is Hana going?', answer: 'Millbridge', wrong: ['Brookfield', 'Back home'] },
        { q: 'How far away is her stop?', answer: 'About forty minutes', wrong: ['About fourteen minutes', 'About four hours'] },
        { q: 'What did Hana forget?', answer: 'Her water bottle', wrong: ['Her book', 'Her ticket'] },
      ],
    },
    {
      title: "At the Doctor's",
      a: { name: 'Lucas', voice: 'm' },
      b: { name: 'Dr Obi', voice: 'f' },
      lines: [
        ['a', 'Good morning, doctor. I feel terrible.'],
        ['b', "What's the problem?"],
        ['a', 'I have a sore throat and a headache.'],
        ['b', 'When did it start?'],
        ['a', "On Monday. And I didn't sleep well last night."],
        ['b', 'Do you have a temperature?'],
        ['a', 'No, but I feel very tired.'],
        ['b', 'Drink lots of warm water and rest for three days.'],
      ],
      questions: [
        { q: 'When did the problem start?', answer: 'On Monday', wrong: ['Last night', 'Three days ago'] },
        { q: 'Does Lucas have a temperature?', answer: "No, he doesn't", wrong: ['Yes, a high one', 'Yes, since Monday'] },
        { q: 'How long should Lucas rest?', answer: 'Three days', wrong: ['One week', 'Two days'] },
      ],
    },
    {
      title: 'Market Day',
      a: { name: 'Rosa', voice: 'f' },
      b: { name: 'Ivan', voice: 'm' },
      lines: [
        ['a', 'Hi! How much are the tomatoes?'],
        ['b', "Two dollars a kilo. They're very fresh today."],
        ['a', "I'll take two kilos, please. Do you have any strawberries?"],
        ['b', 'Sorry, we sold them all this morning. We have cherries.'],
        ['a', "Hmm, no, thanks. My son doesn't like cherries."],
        ['b', "Here you are. That's four dollars."],
      ],
      questions: [
        { q: 'How many kilos of tomatoes does Rosa buy?', answer: 'Two', wrong: ['One', 'Four'] },
        { q: 'Why are there no strawberries?', answer: 'They sold them all', wrong: ["They aren't fresh", "It isn't summer"] },
        { q: "Why doesn't Rosa buy cherries?", answer: "Her son doesn't like them", wrong: ['They are too expensive', "They aren't fresh"] },
      ],
    },
    {
      title: 'The Dragon-Sitter',
      a: { name: 'Freya', voice: 'f' },
      b: { name: 'Jun', voice: 'm' },
      lines: [
        ['a', 'Jun, can you look after my dragon this weekend?'],
        ['b', 'Sure! What does he eat?'],
        ['a', 'He eats fish twice a day, in the morning and in the evening.'],
        ['b', 'Only fish? No meat?'],
        ['a', 'Never meat! It makes him sneeze fire.'],
        ['b', 'Ha! And does he need a walk?'],
        ['a', 'Yes, a long walk every afternoon. But keep him away from the lake.'],
      ],
      questions: [
        { q: 'How often does the dragon eat?', answer: 'Twice a day', wrong: ['Once a day', 'Three times a day'] },
        { q: 'What happens if he eats meat?', answer: 'He sneezes fire', wrong: ['He falls asleep', 'He gets angry'] },
        { q: 'Where should Jun NOT take the dragon?', answer: 'To the lake', wrong: ['To the park', 'To the forest'] },
      ],
    },
  ],
  // B1
  [
    {
      title: 'Moving House',
      a: { name: 'Amara', voice: 'f' },
      b: { name: 'Felix', voice: 'm' },
      lines: [
        ['a', 'Felix, are you still free on Saturday to help me move?'],
        ['b', 'Yes, but I have to leave by four. What time are you starting?'],
        ['a', 'The van is coming at nine, so could you get here at half past eight?'],
        ['b', "That's fine. Is the new flat far from here?"],
        ['a', "Not really, about twenty minutes by car. It's on the third floor, though, and there's no lift."],
        ['b', 'Oh no. Your sofa is going to be a problem, then.'],
        ['a', "I know. My cousin Dev said he'd come too, so there'll be three of us."],
        ['b', "Good. I'll bring some pizza for lunch. We'll need the energy!"],
      ],
      questions: [
        { q: 'What time should Felix arrive?', answer: 'Half past eight', wrong: ["Nine o'clock", "Four o'clock"] },
        { q: 'How many people will do the moving?', answer: 'Three', wrong: ['Two', 'Four'] },
        { q: 'Why will the sofa be a problem?', answer: 'There is no lift', wrong: ['The van is too small', 'The flat is far away'] },
      ],
    },
    {
      title: 'Interview Nerves',
      a: { name: 'Kenji', voice: 'm' },
      b: { name: 'Lucia', voice: 'f' },
      lines: [
        ['a', "I've got a job interview tomorrow at the bookshop on Hill Street."],
        ['b', "That's great! Are you nervous?"],
        ['a', "Very. I've never had a real interview before."],
        ['b', 'Just be yourself. What do you know about the shop?'],
        ['a', 'They sell new and second-hand books, and they run a reading club for kids on Fridays.'],
        ['b', 'Perfect. Mention that you helped at the school library last year.'],
        ['a', "Good idea. I'd forgotten about that."],
        ['b', "And don't be late. Leave home early in case the bus is slow."],
      ],
      questions: [
        { q: 'Where is the interview?', answer: 'At a bookshop', wrong: ['At a school library', 'At a bus station'] },
        { q: 'When is the reading club?', answer: 'On Fridays', wrong: ['On Saturdays', 'Every day'] },
        { q: 'What is Lucia mainly doing?', answer: 'Giving Kenji advice', wrong: ['Asking for a job', 'Planning a book club'] },
      ],
    },
    {
      title: 'The River Project',
      a: { name: 'Zainab', voice: 'f' },
      b: { name: 'Mateo', voice: 'm' },
      lines: [
        ['a', 'Mateo, have you finished your part of the project on rivers?'],
        ['b', "Almost. I've written about pollution, but I still need some pictures."],
        ['a', "The deadline is Thursday, remember. I don't want to rush on Wednesday night."],
        ['b', 'I know, I know. Could you check my writing tonight?'],
        ['a', "Sure, send it before eight. I've got football practice after that."],
        ['b', "Okay. By the way, who's doing the map?"],
        ['a', 'Nobody! I thought you were.'],
        ['b', "Right, let's do it together tomorrow at lunch."],
      ],
      questions: [
        { q: 'What does Mateo say he still needs?', answer: 'Some pictures', wrong: ['More writing', 'A new topic'] },
        { q: 'When must Mateo send his writing?', answer: 'Before eight', wrong: ['After football', 'On Thursday'] },
        { q: 'What problem do they discover?', answer: 'Nobody has done the map', wrong: ['The deadline has changed', 'Mateo lost his work'] },
      ],
    },
    {
      title: 'The Potion Shop',
      a: { name: 'Ingrid', voice: 'f' },
      b: { name: 'Ravi', voice: 'm' },
      lines: [
        ['b', "Good afternoon. I need something for my sister. She can't sleep."],
        ['a', 'I see. How long has she had this problem?'],
        ['b', "About two weeks. She's got important exams soon."],
        ['a', "Then I'd suggest the lavender potion. Three drops in warm milk before bed."],
        ['b', "Is it safe? She's only fifteen."],
        ['a', "Completely safe. But she shouldn't take it for more than a week."],
        ['b', 'Great. How much is it?'],
        ['a', 'Twelve silver coins. And tell her to stop studying late at night, too!'],
      ],
      questions: [
        { q: 'How many drops should the sister take?', answer: 'Three', wrong: ['Two', 'Twelve'] },
        { q: 'What is the longest she should use it?', answer: 'One week', wrong: ['Two weeks', 'Fifteen days'] },
        { q: "Why probably can't the sister sleep?", answer: "She's worried about exams", wrong: ['She drinks warm milk', 'She is too young'] },
      ],
    },
  ],
  // B2
  [
    {
      title: 'A Cancelled Flight',
      a: { name: 'Chloe', voice: 'f' },
      b: { name: 'Tariq', voice: 'm' },
      lines: [
        ['a', 'Hi, my flight to Lisbon has just been cancelled. What are my options?'],
        ['b', "I'm sorry about that. The next direct flight leaves tomorrow at seven a.m., but it's almost full."],
        ['a', "Tomorrow? I've got a conference presentation at ten tomorrow morning."],
        ['b', "In that case, there's a connection through Madrid tonight. You'd land in Lisbon at half past one in the morning."],
        ['a', "That's late, but at least I'd make it. Would I have to pay extra?"],
        ['b', 'No, since the cancellation was our fault, the change is free. We can also give you a meal voucher for the wait.'],
        ['a', "That's something, I suppose. And what about my suitcase?"],
        ['b', "It'll be transferred automatically, so you won't need to collect it in Madrid."],
        ['a', 'Fine, book me on that one, please.'],
      ],
      questions: [
        { q: "When is Chloe's presentation?", answer: 'At ten tomorrow', wrong: ['At seven tomorrow', 'At half past one'] },
        { q: 'Why is the change free?', answer: 'The airline caused the problem', wrong: ['She has a voucher', 'The flight was full'] },
        { q: 'Which option does Chloe choose?', answer: 'Flying via Madrid tonight', wrong: ['The direct flight tomorrow', 'Staying at a hotel'] },
      ],
    },
    {
      title: 'The Kitchen Problem',
      a: { name: 'Noor', voice: 'f' },
      b: { name: 'Sam', voice: 'm' },
      lines: [
        ['a', "Sam, have you got a minute? There's something I wanted to talk about."],
        ['b', "Sure, what's up?"],
        ['a', 'It\'s the kitchen. I keep finding dirty pans in the sink when I get home from work.'],
        ['b', "Ah. Sorry, I've been cooking late because of my new shifts."],
        ['a', "I get that, and I don't mind you cooking late. I'd just rather not start my evening by washing up."],
        ['b', 'Fair enough. What if I wash everything before I go to bed, however late it is?'],
        ['a', 'That would be great. And maybe we could make a cleaning rota for the weekends?'],
        ['b', "Good idea. I'll put one on the fridge tomorrow."],
      ],
      questions: [
        { q: 'Why has Sam been cooking late?', answer: 'His new work shifts', wrong: ['He enjoys late dinners', 'Noor asked him to'] },
        { q: 'What does Sam promise to do?', answer: 'Wash up before bed', wrong: ['Stop cooking late', 'Cook for Noor'] },
        { q: 'How would you describe the conversation?', answer: 'Polite and constructive', wrong: ['Angry and unfriendly', 'Funny but pointless'] },
      ],
    },
    {
      title: 'A Summer with Dragons',
      a: { name: 'Mei', voice: 'f' },
      b: { name: 'Okonkwo', voice: 'm' },
      lines: [
        ['b', "So, you'd like the dragon-sitting job for the summer. Have you worked with dragons before?"],
        ['a', 'Not dragons exactly, but I spent two years on a farm looking after horses and goats.'],
        ['b', "That's useful. Dragons are bigger, of course, but the routine is surprisingly similar."],
        ['a', 'What would a typical day involve?'],
        ['b', 'Feeding at dawn, cleaning the cave, and flying practice in the afternoon, weather permitting.'],
        ['a', "Flying practice? I'm afraid I'm not very good with heights."],
        ['b', "Don't worry, you'd stay on the ground holding the safety rope. Rufus does the flying."],
        ['a', "That's a relief. And would I be working alone?"],
        ['b', 'Only at weekends. During the week, my assistant Ilse would be with you.'],
      ],
      questions: [
        { q: 'What experience does Mei have?', answer: 'Caring for farm animals', wrong: ['Working with dragons', 'Teaching flying lessons'] },
        { q: 'When would Mei work alone?', answer: 'At weekends', wrong: ['During the week', 'In the afternoons'] },
        { q: 'Why is Mei relieved?', answer: "She won't have to fly", wrong: ["She'll work with Ilse", 'The job is short'] },
      ],
    },
    {
      title: 'Choosing a Laptop',
      a: { name: 'Elena', voice: 'f' },
      b: { name: 'Kwame', voice: 'm' },
      lines: [
        ['a', 'Kwame, you know about computers. Should I buy the cheaper laptop or the one with the bigger screen?'],
        ['b', 'It depends. What will you mostly use it for?'],
        ['a', 'Writing essays, video calls and a bit of photo editing.'],
        ['b', 'Then honestly, the cheaper one would do the job. The big screen is nice, but it makes the laptop heavy.'],
        ['a', "That's a point. I carry it to university every day."],
        ['b', "Exactly. Spend the money you save on extra memory instead. It'll make a bigger difference for photo editing."],
        ['a', 'Can I add memory later, or do I have to choose now?'],
        ['b', "On that model you have to choose when you buy it, so don't wait."],
      ],
      questions: [
        { q: 'What will Elena mostly use the laptop for?', answer: 'Essays, calls and photos', wrong: ['Games and films', 'Programming and music'] },
        { q: 'What should she spend the saved money on?', answer: 'Extra memory', wrong: ['A bigger screen', 'A lighter bag'] },
        { q: 'Why does the weight matter to Elena?', answer: 'She carries it daily', wrong: ['She edits photos', 'It costs more'] },
      ],
    },
  ],
  // C1
  [
    {
      title: 'The Promotion',
      a: { name: 'Farah', voice: 'f' },
      b: { name: 'Daniel', voice: 'm' },
      lines: [
        ['a', 'So, I hear congratulations are in order. Head of the design team, no less.'],
        ['b', "Thanks, although I'm not sure 'congratulations' is quite the word yet. I haven't accepted."],
        ['a', "Really? I'd have thought you'd jump at it."],
        ['b', 'On paper, yes. But it would mean managing people who were my peers until last week, including Marco.'],
        ['a', "Ah. And Marco applied for the same role, didn't he?"],
        ['b', "He did, and he's been rather quiet with me ever since the announcement."],
        ['a', "For what it's worth, I think he'll come round. He's disappointed, not resentful."],
        ['b', "I hope you're right. I'd rather turn it down than spend a year walking on eggshells."],
        ['a', 'Well, before you decide, why not just talk to him? You might be surprised.'],
      ],
      questions: [
        { q: 'What role has Daniel been offered?', answer: 'Head of the design team', wrong: ["Marco's assistant", 'Head of marketing'] },
        { q: 'Why is Daniel hesitant to accept?', answer: "He'd manage former peers", wrong: ['The salary is too low', 'He dislikes design work'] },
        { q: 'What does Farah imply about Marco?', answer: 'He will accept it eventually', wrong: ['He is secretly angry', 'He plans to resign'] },
      ],
    },
    {
      title: 'A Faulty Grinder',
      a: { name: 'Yusuf', voice: 'm' },
      b: { name: 'Clara', voice: 'f' },
      lines: [
        ['a', "Hello, I bought this coffee grinder here three weeks ago and it's already stopped working."],
        ['b', "I'm sorry to hear that. Do you have the receipt with you?"],
        ['a', "I'm afraid I've mislaid it, but I paid by card, so there should be a record."],
        ['b', 'That should be fine; we can look it up. Has it been used for anything other than coffee?'],
        ['a', "Well, I did grind some spices once or twice. Surely that's not a problem?"],
        ['b', 'Strictly speaking, the guarantee only covers coffee beans, since spices can damage the blades.'],
        ['a', "That wasn't mentioned anywhere when I bought it."],
        ['b', "It's in the manual, although I appreciate nobody reads those. Tell you what, I'll offer a replacement this time, as a gesture of goodwill."],
        ['a', "That's very fair of you. I'll stick to coffee from now on."],
      ],
      questions: [
        { q: 'How can Yusuf prove he bought it?', answer: 'Through his card payment', wrong: ['With the receipt', 'With the manual'] },
        { q: 'Why might the guarantee not apply?', answer: 'He ground spices in it', wrong: ["It's over a month old", 'He lost the box'] },
        { q: 'Why does Clara offer a replacement?', answer: 'As goodwill, not obligation', wrong: ['The guarantee requires it', 'The receipt proves it'] },
      ],
    },
    {
      title: "The Apprentice's Shortcut",
      a: { name: 'Master Selene', voice: 'f' },
      b: { name: 'Tobias', voice: 'm' },
      lines: [
        ['b', "Master Selene, I've finished copying the spell book. Shall I start on the potions?"],
        ['a', 'Finished already? The entire book?'],
        ['b', 'Well, most of it. I skipped the chapter on weather charms, since we never use them.'],
        ['a', 'I see. And did it occur to you that we might need them one day?'],
        ['b', "I suppose it didn't. But the harvest festival isn't until autumn, surely."],
        ['a', 'Precisely, and who do you think the village will ask for sunshine that day?'],
        ['b', "Ah. Us. I'll go back and copy it properly this afternoon."],
        ['a', 'Good. The potions can wait. A shortcut today is usually a longer road tomorrow.'],
      ],
      questions: [
        { q: 'Which part did Tobias skip?', answer: 'The weather charms chapter', wrong: ['The potions chapter', 'The festival chapter'] },
        { q: 'Why did Tobias skip it?', answer: 'He thought it was useless', wrong: ['It was too difficult', 'Selene told him to'] },
        { q: "What is Selene's attitude?", answer: 'Critical of his shortcut', wrong: ['Pleased with his speed', 'Uninterested in the book'] },
      ],
    },
    {
      title: 'The Lakeside Cottage',
      a: { name: 'Leila', voice: 'f' },
      b: { name: 'Arjun', voice: 'm' },
      lines: [
        ['a', 'So, have you had a look at the cottage I sent you? The one by the lake?'],
        ['b', "I have. It looks lovely, it's just... rather remote, isn't it?"],
        ['a', "That's rather the point. No signal, no emails, no distractions."],
        ['b', 'No signal at all? What if the office needs to reach me?'],
        ['a', "Arjun, you're on holiday. The office will survive a week without you."],
        ['b', "I know, I know. It's just that the product launch is the week after we get back."],
        ['a', "Which is exactly why you need a proper break beforehand. You'll be exhausted otherwise."],
        ['b', "Fine, you've convinced me. But I'm bringing a stack of books, since there's no Wi-Fi either."],
        ['a', "Deal. I'll book it tonight before someone else does."],
      ],
      questions: [
        { q: 'Where is the cottage?', answer: 'By a lake', wrong: ['In the mountains', 'Near the office'] },
        { q: 'What worries Arjun at first?', answer: 'Being unreachable for work', wrong: ['The price of the cottage', 'Reading too many books'] },
        { q: 'How does the conversation end?', answer: 'Arjun agrees to go', wrong: ['They choose another place', 'Leila cancels the trip'] },
      ],
    },
  ],
]
