import type { ByLevel, Letter } from './types'

// Guild Letters: read a letter and write a reply.
export const LETTERS: ByLevel<Letter> = [
  // A1
  [
    {
      from: 'Nia, your new pen friend',
      body: 'Hi! My name is Nia. I am twelve. I like cats and music. What do you like?',
      task: 'Write back. Say your name, your age and what you like.',
      minWords: 12,
      keys: [['my name is', 'i am', "i'm"], ['i like', 'i love']],
      sample: 'Hi Nia! My name is Sam. I am thirteen. I like football and pizza. I love dogs too!',
    },
    {
      from: 'Bram, the innkeeper',
      body: 'Hello, traveller! Welcome to my inn. What do you want for dinner? We have soup, fish and bread.',
      task: 'Choose your dinner and a drink. Say please and thank you.',
      minWords: 12,
      keys: [['please'], ['thank you', 'thanks'], ['soup', 'fish', 'bread']],
      sample: 'Hello Bram! I want fish and bread, please. And a glass of water, please. Thank you very much!',
    },
    {
      from: 'Rosa, your classmate',
      body: 'Hi! I am at home today. I am sick. What is our homework?',
      task: 'Tell Rosa the homework and say you hope she feels better.',
      minWords: 12,
      keys: [['homework', 'page', 'read'], ['get well', 'feel better']],
      sample: 'Hi Rosa! The homework is page ten in the English book. Please read the story too. Get well soon!',
    },
    {
      from: 'Pip, the baby dragon',
      body: 'Hello! I am Pip. I am small and green. I live in a cave. Where do you live?',
      task: 'Tell Pip where you live and describe your home.',
      minWords: 12,
      keys: [['i live', 'my home', 'my house'], ['big', 'small', 'nice', 'old', 'new']],
      sample: 'Hi Pip! I live in a small flat in the city. My home has two bedrooms and a nice kitchen.',
    },
    {
      from: 'Ms Tanaka, your teacher',
      body: 'Hello, class! On Saturday we have a picnic in the park. What food can you bring?',
      task: 'Answer your teacher. Say what food you can bring.',
      minWords: 12,
      keys: [['i can bring', 'i can'], ['sandwich', 'fruit', 'cake', 'juice', 'apple', 'cookie']],
      sample: 'Hello Ms Tanaka! I can bring apples and some orange juice. My mum can make a cake too. See you on Saturday!',
    },
  ],
  // A2
  [
    {
      from: 'Daniel, your cousin',
      body: "Hi! I'm coming to your city next month for three days. What can we do there? Is there a good place to eat?",
      task: 'Suggest two things to do and one place to eat.',
      minWords: 20,
      keys: [['we can', "let's", 'you can'], ['restaurant', 'cafe', 'food']],
      sample: 'Hi Daniel! Great news! We can visit the old castle and walk by the river. There is also a big market on Sundays. My favourite place to eat is a small restaurant near my house. The pizza there is really good. See you soon!',
    },
    {
      from: 'Fatima, a friend from school',
      body: 'Hi! I missed you at the party last Saturday. Where were you? What did you do?',
      task: 'Explain where you were and what you did last weekend.',
      minWords: 20,
      keys: [['was', 'were'], ['went', 'visited', 'watched', 'played', 'stayed']],
      sample: "Hi Fatima! Sorry I missed the party. I was at my grandparents' house in the country. On Saturday we went fishing in the lake, and on Sunday I played cards with my grandad. It was quiet but fun!",
    },
    {
      from: 'Hugo, the stable master',
      body: 'Hello! One of our horses is ill, so I need some help this week. Can you come to the stables? Which days are you free?',
      task: 'Say which days you can help and at what time.',
      minWords: 20,
      keys: [['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], ["o'clock", 'morning', 'afternoon', 'evening']],
      sample: "Hello Hugo! I'm sorry about your horse. I can help on Tuesday and Thursday this week. I finish school at three o'clock, so I can come in the afternoon, at about four. Is that okay?",
    },
    {
      from: 'Lena, your neighbour',
      body: "Hi! I'm going on holiday for a week. Could you water my plants and feed my fish? I'll leave the key under the mat.",
      task: 'Reply and say yes. Ask one question about the job.',
      minWords: 20,
      keys: [['yes', 'of course', 'sure', 'no problem'], ['how often', 'how much', 'when', 'what time']],
      sample: 'Hi Lena! Of course, no problem. I can water your plants and feed your fish. How often do the plants need water? And how much food does the fish eat? Have a great holiday!',
    },
    {
      from: 'Zara, a young witch',
      body: "Hello! I'm new at the School of Magic and I don't know anyone. What was your first day at school like? Were you nervous?",
      task: 'Tell Zara about your first day at school and give her a tip.',
      minWords: 20,
      keys: [['was', 'were', 'felt'], ['try to', 'you should', "don't worry"]],
      sample: "Hi Zara! My first day at school was scary. I was very nervous and I didn't speak to anyone in the morning. But at lunch a girl sat next to me and we became friends. Don't worry! Try to smile and say hello to people.",
    },
  ],
  // B1
  [
    {
      from: 'Marta, your friend',
      body: "I've been offered two part-time jobs: one in a bookshop, and one in a busy cafe that pays more. I love books, but I really need money for my trip next summer. Which one should I take?",
      task: 'Give Marta your advice and explain your reasons.',
      minWords: 35,
      keys: [['because', 'so', 'since'], ['should', 'could', "why don't you", 'i think']],
      sample: "Hi Marta! What a nice problem to have! I think you should take the cafe job, because your trip is really important to you. You'll save money faster, so you can travel next summer. You could still buy books with your first salary! Why don't you visit the bookshop at weekends instead?",
    },
    {
      from: "Captain Rhea, head of the Explorers' Guild",
      body: 'We are looking for volunteers for a three-day trip to the Crystal Caves. The journey is hard, and you will sleep in tents. Tell us why you want to join and what skills you have.',
      task: 'Apply for the trip. Describe your skills and experience.',
      minWords: 35,
      keys: [['i have', 'i can', "i've"], ['because', 'since', 'so']],
      sample: "Dear Captain Rhea, I would like to join the trip to the Crystal Caves because I love exploring new places. I have camped in the mountains many times, so sleeping in a tent is not a problem for me. I can also cook simple meals and read maps well. I hope you will choose me.",
    },
    {
      from: 'Mr Okafor, your landlord',
      body: "I'm sorry to hear that the heating in your flat isn't working. Can you describe the problem in more detail? When did it start, and what have you already tried?",
      task: 'Describe the problem, when it began, and what you have tried.',
      minWords: 35,
      keys: [['since', 'ago', 'last'], ["i've tried", 'i have tried', 'i tried', "i've checked", 'i checked']],
      sample: "Dear Mr Okafor, thank you for your quick reply. The heating stopped working three days ago. The radiators in the bedroom are completely cold, and the one in the living room is only warm. I've tried turning the boiler off and on again, but nothing changed. Could someone come this week?",
    },
    {
      from: 'Sven, an exchange student',
      body: "I'm coming to your country for a month next spring. What should I pack? And is there any food I really must try?",
      task: 'Advise Sven on what to bring and recommend some food.',
      minWords: 35,
      keys: [['should', 'must', 'had better'], ['recommend', 'try', 'definitely']],
      sample: "Hi Sven! Spring here can be warm during the day but cold at night, so you should pack a light jacket and a sweater. You must bring comfortable shoes, because we walk a lot. As for food, you should definitely try our fresh bread with cheese and honey. I'm sure you'll love it!",
    },
    {
      from: 'Grandma Lucia',
      body: "I've decided to learn how to use a smartphone at last! But everything is so small and confusing. How did you learn? Have you got any tips for me?",
      task: 'Give your grandma some practical tips.',
      minWords: 35,
      keys: [['first', 'then', 'after that'], ['should', 'could', 'try']],
      sample: "Dear Grandma, I'm so proud of you! First, you should make the letters bigger in the settings, so everything is easier to read. Then try to learn one thing at a time, like calling and sending messages. After that, you could learn how to take photos. I can help you on Sunday!",
    },
  ],
  // B2
  [
    {
      from: 'Ms Chen, manager of the Harbour View Hotel',
      body: 'Thank you for staying with us. We noticed you left two days early and did not use the rest of your booking. We would love to know if there was a problem with your stay.',
      task: 'Write a polite complaint explaining what went wrong and what you expect.',
      minWords: 50,
      keys: [['unfortunately', 'however', 'although'], ['would appreciate', 'would like', 'could you']],
      sample: "Dear Ms Chen, thank you for your message. Unfortunately, there were several problems during my stay. Although I had booked a quiet room, mine was directly above the kitchen, and the noise started at five every morning. When I asked to change rooms, I was told none were available. I would appreciate a refund for the two nights I did not use. Kind regards, Laila Haddad",
    },
    {
      from: 'Tariq, a friend',
      body: "I'm thinking of quitting university to start my own business selling handmade furniture. My parents are furious. What would you do if you were me?",
      task: 'Give balanced advice using conditionals.',
      minWords: 50,
      keys: [['if i were you', 'if you', 'would'], ['on the other hand', 'however', 'although']],
      sample: "Hi Tariq, I can see why you're excited, because your furniture is beautiful. If I were you, I wouldn't quit completely, though. You could take a year off instead, which would give you time to test the business. On the other hand, if you wait too long, you might lose your enthusiasm. Whatever you decide, try to explain your plan calmly to your parents.",
    },
    {
      from: "Guildmaster Oona of the Alchemists' Guild",
      body: "Our guild wants to open a potion stall at the city market, but we can't agree whether to sell cheap everyday remedies or rare, expensive potions. As a regular customer, what is your opinion?",
      task: 'Give your opinion and support it with reasons and an example.',
      minWords: 50,
      keys: [['in my opinion', 'i believe', 'i think'], ['for example', 'for instance', 'such as'], ['whereas', 'while', 'on the other hand', 'however']],
      sample: "Dear Guildmaster Oona, in my opinion, the stall should focus on everyday remedies. Most people at the market are shopping for simple things, such as cough syrups or sleeping drops, whereas rare potions are only bought by a few collectors. For example, my neighbour buys a cold remedy every winter. However, you could keep one or two rare potions on display to attract attention.",
    },
    {
      from: 'Leon, organiser of the city charity run',
      body: "Unfortunately, our charity run has been cancelled because of the storm warning. We know many of you trained hard. Would you prefer a refund or a place in next month's event?",
      task: 'State your preference and suggest how the organisers could communicate better.',
      minWords: 50,
      keys: [['prefer', 'would rather'], ['should have', 'could have', 'it would be']],
      sample: "Dear Leon, thank you for letting us know. I would prefer a place in next month's event, since I have been training for weeks and would hate to waste that effort. However, I only found out about the cancellation when I arrived at the start line. You should have sent a text message the night before. In future, it would be helpful to post updates online as well.",
    },
    {
      from: 'Aunt Sadia',
      body: "Your cousin wants to adopt a dog, but she works long hours and lives in a small flat. I'm worried it's a bad idea. You've had dogs for years. What do you think?",
      task: 'Share your experience and suggest possible solutions.',
      minWords: 50,
      keys: [['in my experience', "i've had", 'i have had'], ['unless', 'as long as', 'provided']],
      sample: "Dear Aunt Sadia, I understand your concern. In my experience, dogs can be happy in small flats, as long as they get enough exercise and company. The long hours are the real problem. Unless she can pay a dog walker or ask a neighbour to help, the dog will be lonely. Perhaps she could adopt an older, calmer dog, which usually needs less attention than a puppy.",
    },
  ],
  // C1
  [
    {
      from: 'Amani Mwangi, editor of a city magazine',
      body: "We're preparing an issue on how technology is changing family life, and we'd welcome short opinion pieces from readers. Is technology bringing families closer together or pushing them apart?",
      task: 'Write a short opinion piece with a clear position and a concession.',
      minWords: 70,
      keys: [['admittedly', 'while it is true', 'granted', 'although'], ['nevertheless', 'nonetheless', 'even so'], ['ultimately', 'on balance', 'in conclusion']],
      sample: "Admittedly, it is hard to ignore the sight of a family sitting around a dinner table, each member absorbed in a different screen. Nevertheless, I would argue that technology, used wisely, brings families closer rather than pushing them apart. My grandparents, who live on another continent, now watch my younger brother grow up through weekly video calls, something unimaginable a generation ago. The problem lies not in the devices themselves but in the absence of boundaries. On balance, technology is a tool, and it reflects the habits of the people who use it.",
    },
    {
      from: 'Rowan, a colleague',
      body: "I've been asked to lead the new project, but I'm already overloaded and I'm worried that saying no will harm my career. You've been in a similar position. How did you handle it?",
      task: 'Describe your experience and advise Rowan diplomatically.',
      minWords: 70,
      keys: [['when i was', 'i found', 'in my case', 'i remember'], ['might', 'perhaps', 'it may be worth', 'you could']],
      sample: "Hi Rowan, I completely understand the dilemma. In my case, I was offered a similar role two years ago while I was juggling three deadlines. Rather than refusing outright, I asked my manager which of my current tasks could be handed over if I accepted. I found that this reframed the conversation: instead of seeming unwilling, I came across as someone thinking strategically. It may be worth trying the same approach. Perhaps you could also suggest a start date after your current project ends. Good luck!",
    },
    {
      from: 'The High Council of Wizards',
      body: 'The Council is considering banning flying brooms in the city centre after several accidents. Before a decision is made, we invite residents to submit their views, including any alternative proposals.',
      task: 'Write a formal response arguing your position and proposing an alternative.',
      minWords: 70,
      keys: [['i would like to', 'i am writing'], ['furthermore', 'moreover', 'in addition'], ['propose', 'suggest', 'recommend']],
      sample: "Dear Members of the Council, I am writing to express my concern about the proposed ban on flying brooms. While the recent accidents are undeniably worrying, a complete ban would punish thousands of careful riders who rely on brooms to get to work. Furthermore, it would force more carts onto streets that are already congested. I would therefore like to propose an alternative: designated flight lanes at a fixed height, combined with compulsory safety training for new riders. I am confident this would reduce accidents without restricting everyone's freedom.",
    },
    {
      from: 'Julien, owner of a small restaurant',
      body: "Our recent online reviews have been harsh, mainly about slow service. I'm reluctant to hire more staff because costs are rising. As a loyal customer, what would you suggest?",
      task: 'Offer tactful, realistic suggestions.',
      minWords: 70,
      keys: [['might', 'could', 'perhaps'], ['instead of', 'rather than', 'whereas'], ['not only', 'as well as', 'in addition']],
      sample: "Dear Julien, I'm sorry to hear about the reviews, especially as your food is consistently excellent. Having eaten there often, I suspect the delays come from the kitchen rather than from your waiting staff. Perhaps you could simplify the menu slightly, which would not only speed up service but also reduce waste and costs. Instead of hiring a full-time employee, you might consider an extra part-time helper for Friday and Saturday evenings only. A short note on the menu explaining that dishes are cooked fresh could also manage expectations.",
    },
    {
      from: 'Ms Yara Haddad, your former teacher',
      body: "I'm writing a reference letter for your scholarship application. Could you remind me of an achievement you're proud of and explain what you learned from it? Please be specific.",
      task: 'Describe an achievement and reflect on what it taught you.',
      minWords: 70,
      keys: [['proud', 'achievement'], ['taught me', 'i learned', 'i realised', 'i realized'], ['looking back', 'in hindsight', 'with hindsight']],
      sample: "Dear Ms Haddad, thank you so much for agreeing to write the reference. The achievement I'm proudest of is organising the school's first charity book fair in my final year. Although we raised over two thousand dollars, the process was far from smooth: two volunteers dropped out the week before, and I had to reorganise everything at short notice. Looking back, that crisis taught me more than the success itself. I learned to delegate, to stay calm under pressure and to ask for help before problems grew. Best wishes, Nadia",
    },
  ],
]
