import type { ByLevel, TypeWord } from './types'

// Rune Type: read the clue, type the word. Index 0..4 = A1..C1.
export const RUNE_WORDS: ByLevel<TypeWord> = [
  // A1: 3-6 letters
  [
    { word: 'bread', clue: 'You make toast from this.' },
    { word: 'water', clue: 'A clear drink with no taste.' },
    { word: 'school', clue: 'Children go here to learn.' },
    { word: 'sister', clue: 'A girl with the same parents as you.' },
    { word: 'green', clue: 'The colour of grass.' },
    { word: 'train', clue: 'It runs on rails and carries people.' },
    { word: 'apple', clue: 'A round red or green fruit.' },
    { word: 'sleep', clue: 'What you do in bed at night.' },
    { word: 'dragon', clue: 'A big flying animal that breathes fire.' },
    { word: 'rain', clue: 'Water that falls from clouds.' },
    { word: 'chair', clue: 'You sit on this at a table.' },
    { word: 'friday', clue: 'The day after Thursday.' },
    { word: 'happy', clue: 'Feeling good and smiling.' },
    { word: 'cup', clue: 'You drink tea or coffee from it.' },
    { word: 'wand', clue: 'A magic stick that a wizard holds.' },
  ],
  // A2: 4-7 letters
  [
    { word: 'kitchen', clue: 'The room where you cook food.' },
    { word: 'village', clue: 'A very small town in the country.' },
    { word: 'weather', clue: 'Rain, sun, wind and snow outside.' },
    { word: 'dentist', clue: 'A doctor who looks after your teeth.' },
    { word: 'borrow', clue: 'Take something and give it back later.' },
    { word: 'ticket', clue: 'A paper you need to travel or watch shows.' },
    { word: 'healthy', clue: 'Strong and not ill.' },
    { word: 'castle', clue: 'A large old stone building for kings.' },
    { word: 'cheap', clue: 'It does not cost much money.' },
    { word: 'journey', clue: 'Travelling from one place to another.' },
    { word: 'potion', clue: 'A magic drink made by a witch.' },
    { word: 'quiet', clue: 'Making very little noise.' },
    { word: 'bridge', clue: 'You cross a river on this.' },
    { word: 'invite', clue: 'Ask someone to come to your party.' },
    { word: 'forest', clue: 'A large area with many trees.' },
  ],
  // B1: 5-9 letters
  [
    { word: 'necessary', clue: 'Needed; you must have it.' },
    { word: 'rhythm', clue: 'A regular beat in music.' },
    { word: 'receive', clue: 'Get something that someone sends you.' },
    { word: 'separate', clue: 'Apart; not joined together.' },
    { word: 'believe', clue: 'Think that something is true.' },
    { word: 'library', clue: 'A place where you borrow books.' },
    { word: 'schedule', clue: 'A plan showing when things will happen.' },
    { word: 'foreign', clue: 'From another country.' },
    { word: 'surprise', clue: 'Something you did not expect.' },
    { word: 'guarantee', clue: 'A firm promise that something will happen.' },
    { word: 'knight', clue: 'A soldier in armour who serves a king.' },
    { word: 'luggage', clue: 'Bags and cases you take on a trip.' },
    { word: 'weird', clue: 'Very strange or unusual.' },
    { word: 'calendar', clue: 'It shows the days and months of a year.' },
    { word: 'scissors', clue: 'A tool with two blades for cutting paper.' },
  ],
  // B2: 6-11 letters
  [
    { word: 'accommodate', clue: 'Provide a place for someone to stay.' },
    { word: 'embarrass', clue: 'Make someone feel shy and awkward.' },
    { word: 'occurrence', clue: 'Something that happens; an event.' },
    { word: 'definitely', clue: 'Certainly; without any doubt.' },
    { word: 'environment', clue: 'The natural world around us.' },
    { word: 'restaurant', clue: 'A place where you pay to eat meals.' },
    { word: 'conscience', clue: 'The inner voice telling right from wrong.' },
    { word: 'sincerely', clue: 'Honestly; often used to end formal letters.' },
    { word: 'apprentice', clue: 'A young person learning a trade from a master.' },
    { word: 'wednesday', clue: 'The day in the middle of the week.' },
    { word: 'occasion', clue: 'A special event or a particular time.' },
    { word: 'committee', clue: 'A small group chosen to make decisions.' },
    { word: 'rehearsal', clue: 'A practice before the real performance.' },
    { word: 'enchanted', clue: 'Under a magic spell.' },
    { word: 'lightning', clue: 'A bright flash of light in a storm.' },
  ],
  // C1: 7-13 letters
  [
    { word: 'bureaucracy', clue: 'A system with too many official rules and forms.' },
    { word: 'conscientious', clue: 'Careful and hard-working; wanting to do things well.' },
    { word: 'questionnaire', clue: 'A written list of questions for a survey.' },
    { word: 'entrepreneur', clue: 'A person who starts their own business.' },
    { word: 'millennium', clue: 'A period of one thousand years.' },
    { word: 'pronunciation', clue: 'The way a word is spoken aloud.' },
    { word: 'perseverance', clue: 'Continuing to try despite difficulties.' },
    { word: 'liaison', clue: 'A person who connects two groups; communication.' },
    { word: 'surveillance', clue: 'Careful watching of a person or place.' },
    { word: 'idiosyncrasy', clue: 'An unusual personal habit or way of behaving.' },
    { word: 'acquaintance', clue: 'Someone you know, but not a close friend.' },
    { word: 'incantation', clue: 'Magic words spoken to cast a spell.' },
    { word: 'manoeuvre', clue: 'A skilful movement, often of a vehicle.' },
    { word: 'hierarchy', clue: 'A system of ranks from lowest to highest.' },
    { word: 'threshold', clue: 'The entrance of a door; a starting level.' },
  ],
]
