// generated by runecast_fix/boss2/produce.py — placement of the Boss Battle layers.
// golem / hero: % of the 9:16 scene frame; <group>_<pose>: offset + width in % of the base pose box.
type Box = { left?: number; top?: number; width?: number; dx?: number; dy?: number; w?: number }
export const SPRITES: Record<string, Box> = {
  "golem": {
    "left": 44.0,
    "top": 26.8,
    "width": 49.0
  },
  "hero": {
    "left": 7.0,
    "top": 33.7,
    "width": 33.0
  },
  "golem_normal": {
    "dx": 0.0,
    "dy": 0.0,
    "w": 100.0
  },
  "golem_hurt": {
    "dx": 0.0,
    "dy": 0.0,
    "w": 100.0
  },
  "golem_happy": {
    "dx": 0.0,
    "dy": 0.0,
    "w": 100.0
  },
  "golem_beaten": {
    "dx": 0.0,
    "dy": 0.0,
    "w": 100.0
  },
  "hero_normal": {
    "dx": 0.0,
    "dy": 0.0,
    "w": 100.0
  },
  "hero_hurt": {
    "dx": 0.0,
    "dy": 0.0,
    "w": 100.0
  },
  "hero_cheer": {
    "dx": 0.0,
    "dy": 0.0,
    "w": 100.0
  }
}
